### ISSUE TITLE
Can not build this sample

### ISSUE THREAD

**Issue by PunkFleet** [jodconverter/jodconverter-samples#7]
When i 
```
./gradlew :samples:spring-boot-rest:bootRun

```
I got this error, There is import:
```
admin@home jodconverter-samples-main % ./gradlew :samples:spring-boot-rest:bootRun


> Task :samples:spring-boot-rest:bootRun FAILED

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.2)

2023-03-17T16:38:04.869+08:00  INFO 3451 --- [           main] o.j.s.rest.SpringBootRestApplication     : Starting SpringBootRestApplication using Java 17.0.6 with PID 3451 (/Users/admin/Downloads/jodconverter-samples-main/samples/spring-boot-rest/build/classes/java/main started by admin in /Users/admin/Downloads/jodconverter-samples-main/samples/spring-boot-rest)
2023-03-17T16:38:04.871+08:00 DEBUG 3451 --- [           main] o.j.s.rest.SpringBootRestApplication     : Running with Spring Boot v3.0.2, Spring v6.0.4
2023-03-17T16:38:04.871+08:00  INFO 3451 --- [           main] o.j.s.rest.SpringBootRestApplication     : No active profile set, falling back to 1 default profile: "default"
2023-03-17T16:38:05.338+08:00  INFO 3451 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-03-17T16:38:05.343+08:00  INFO 3451 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-03-17T16:38:05.343+08:00  INFO 3451 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.5]
2023-03-17T16:38:05.387+08:00  INFO 3451 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-03-17T16:38:05.388+08:00  INFO 3451 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 495 ms
2023-03-17T16:38:05.425+08:00 DEBUG 3451 --- [           main] o.j.local.office.LocalOfficeUtils        : Default office home set to null
2023-03-17T16:38:05.427+08:00  WARN 3451 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'converterController' defined in file [/Users/admin/Downloads/jodconverter-samples-main/samples/spring-boot-rest/build/classes/java/main/org/jodconverter/sample/rest/ConverterController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'localOfficeManager' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAutoConfiguration.class]: Failed to instantiate [org.jodconverter.core.office.OfficeManager]: Factory method 'localOfficeManager' threw exception with message: officeHome must not be null
2023-03-17T16:38:05.428+08:00  INFO 3451 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-03-17T16:38:05.436+08:00  INFO 3451 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-03-17T16:38:05.444+08:00 ERROR 3451 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'converterController' defined in file [/Users/admin/Downloads/jodconverter-samples-main/samples/spring-boot-rest/build/classes/java/main/org/jodconverter/sample/rest/ConverterController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'localOfficeManager' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAutoConfiguration.class]: Failed to instantiate [org.jodconverter.core.office.OfficeManager]: Factory method 'localOfficeManager' threw exception with message: officeHome must not be null
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1344) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1188) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[spring-context-6.0.4.jar:6.0.4]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.4.jar:6.0.4]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.2.jar:3.0.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.2.jar:3.0.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.2.jar:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.2.jar:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.2.jar:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.2.jar:3.0.2]
        at org.jodconverter.sample.rest.SpringBootRestApplication.main(SpringBootRestApplication.java:23) ~[main/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localOfficeManager' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAutoConfiguration.class]: Failed to instantiate [org.jodconverter.core.office.OfficeManager]: Factory method 'localOfficeManager' threw exception with message: officeHome must not be null
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:645) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1324) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1161) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1405) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-6.0.4.jar:6.0.4]
        ... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jodconverter.core.office.OfficeManager]: Factory method 'localOfficeManager' threw exception with message: officeHome must not be null
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.4.jar:6.0.4]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-6.0.4.jar:6.0.4]
        ... 33 common frames omitted
Caused by: java.lang.NullPointerException: officeHome must not be null
        at org.jodconverter.core.util.AssertUtils.notNull(AssertUtils.java:132) ~[jodconverter-core-4.4.6.jar:4.4.6]
        at org.jodconverter.local.office.LocalOfficeUtils.validateOfficeHome(LocalOfficeUtils.java:356) ~[jodconverter-local-4.4.6.jar:4.4.6]
        at org.jodconverter.local.office.LocalOfficeManager$Builder.build(LocalOfficeManager.java:191) ~[jodconverter-local-4.4.6.jar:4.4.6]
        at org.jodconverter.boot.autoconfigure.JodConverterLocalAutoConfiguration.createOfficeManager(JodConverterLocalAutoConfiguration.java:103) ~[jodconverter-spring-boot-starter-4.4.6.jar:4.4.6]
        at org.jodconverter.boot.autoconfigure.JodConverterLocalAutoConfiguration.localOfficeManager(JodConverterLocalAutoConfiguration.java:151) ~[jodconverter-spring-boot-starter-4.4.6.jar:4.4.6]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.4.jar:6.0.4]
        ... 34 common frames omitted


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':samples:spring-boot-rest:bootRun'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-17.0.6.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
10 actionable tasks: 1 executed, 9 up-to-date
admin@home jodconverter-samples-main % 
```

**Comment by EugenMayer** [comment]
How is that a build issue. You see that spring is already starting?

AFAIU you need libreoffice installed locally since this needs to be started

**Comment by PunkFleet** [comment]
> How is that a build issue. You see that spring is already starting?
> 
> AFAIU you need libreoffice installed locally since this needs to be started

I just install gradle 8.0.2, and cd root path
and beginning type the command following template.
BTW, How i add the template to a blank project in intellij. i thinks this way is good for me

**Comment by DevTrinh** [comment]
> How is that a build issue. You see that spring is already starting?
> 
> AFAIU you need libreoffice installed locally since this needs to be started

How can libreoffice be configured automatically, I want to push it to the server environment
